/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import Imagenes_del_puzzle.Puzzle3x3;
import Imagenes_del_puzzle.Puzzle4x4;

/**
 *
 * @author aleja
 */
public class Ventana_Nivel_De_Dificultad extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_de_Consulta_de_Saldo
     */
    public Ventana_Nivel_De_Dificultad() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("The Puzzle Game - Nivel de dificultad");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Boton_Jugar_Dificultad3x3 = new javax.swing.JButton();
        Boton_Jugar_Dificultad4x4 = new javax.swing.JButton();
        Boton_Volver_Al_Menu = new javax.swing.JButton();
        Boton_VistaPrevia3x3 = new javax.swing.JButton();
        Boton_VistaPrevia4x4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(369, 70));
        setMinimumSize(new java.awt.Dimension(640, 640));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(51, 0, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nivel de dificultad");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 3));
        jLabel1.setInheritsPopupMenu(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 30, 370, 50);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("*Elige la dificultad del juego:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 170, 370, 40);

        Boton_Jugar_Dificultad3x3.setBackground(new java.awt.Color(51, 204, 0));
        Boton_Jugar_Dificultad3x3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 40)); // NOI18N
        Boton_Jugar_Dificultad3x3.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Jugar_Dificultad3x3.setText("3x3 (1 al 8)");
        Boton_Jugar_Dificultad3x3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Normal", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 18), new java.awt.Color(0, 102, 0))); // NOI18N
        Boton_Jugar_Dificultad3x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Jugar_Dificultad3x3ActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Jugar_Dificultad3x3);
        Boton_Jugar_Dificultad3x3.setBounds(50, 230, 260, 90);

        Boton_Jugar_Dificultad4x4.setBackground(new java.awt.Color(255, 153, 0));
        Boton_Jugar_Dificultad4x4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 40)); // NOI18N
        Boton_Jugar_Dificultad4x4.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Jugar_Dificultad4x4.setText("4x4 (1 al 15)");
        Boton_Jugar_Dificultad4x4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dificil", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 18), new java.awt.Color(102, 51, 0))); // NOI18N
        Boton_Jugar_Dificultad4x4.setOpaque(false);
        Boton_Jugar_Dificultad4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Jugar_Dificultad4x4ActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Jugar_Dificultad4x4);
        Boton_Jugar_Dificultad4x4.setBounds(50, 360, 260, 90);

        Boton_Volver_Al_Menu.setBackground(new java.awt.Color(102, 0, 204));
        Boton_Volver_Al_Menu.setFont(new java.awt.Font("Segoe UI Black", 0, 22)); // NOI18N
        Boton_Volver_Al_Menu.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Volver_Al_Menu.setText("<--Volver al menú");
        Boton_Volver_Al_Menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Boton_Volver_Al_Menu.setOpaque(false);
        Boton_Volver_Al_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Volver_Al_MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Volver_Al_Menu);
        Boton_Volver_Al_Menu.setBounds(30, 520, 230, 50);

        Boton_VistaPrevia3x3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 30)); // NOI18N
        Boton_VistaPrevia3x3.setForeground(new java.awt.Color(153, 255, 153));
        Boton_VistaPrevia3x3.setText("Vista previa >>l");
        Boton_VistaPrevia3x3.setContentAreaFilled(false);
        Boton_VistaPrevia3x3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Boton_VistaPrevia3x3.setOpaque(false);
        Boton_VistaPrevia3x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_VistaPrevia3x3ActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_VistaPrevia3x3);
        Boton_VistaPrevia3x3.setBounds(310, 250, 210, 40);

        Boton_VistaPrevia4x4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 30)); // NOI18N
        Boton_VistaPrevia4x4.setForeground(new java.awt.Color(255, 204, 51));
        Boton_VistaPrevia4x4.setText("Vista previa >>l");
        Boton_VistaPrevia4x4.setContentAreaFilled(false);
        Boton_VistaPrevia4x4.setOpaque(false);
        Boton_VistaPrevia4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_VistaPrevia4x4ActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_VistaPrevia4x4);
        Boton_VistaPrevia4x4.setBounds(310, 380, 210, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_del_puzzle/pngtree-modern-dark-color-abstract.jpg"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setMaximumSize(new java.awt.Dimension(640, 640));
        jLabel3.setMinimumSize(new java.awt.Dimension(640, 640));
        jLabel3.setName(""); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(640, 640));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 640, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_Jugar_Dificultad3x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Jugar_Dificultad3x3ActionPerformed
        Ventana_Dificultad_3x3 Ventana = new Ventana_Dificultad_3x3();
        Ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_Boton_Jugar_Dificultad3x3ActionPerformed

    private void Boton_Volver_Al_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Volver_Al_MenuActionPerformed
        Ventana_MenuPrincipal_Juego Ventana = new Ventana_MenuPrincipal_Juego();
        Ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_Boton_Volver_Al_MenuActionPerformed

    private void Boton_VistaPrevia3x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_VistaPrevia3x3ActionPerformed
        Puzzle3x3 Imagen = new Puzzle3x3();
        Imagen.setVisible(true);
    }//GEN-LAST:event_Boton_VistaPrevia3x3ActionPerformed

    private void Boton_VistaPrevia4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_VistaPrevia4x4ActionPerformed
        Puzzle4x4 Imagen = new Puzzle4x4();
        Imagen.setVisible(true);
    }//GEN-LAST:event_Boton_VistaPrevia4x4ActionPerformed

    private void Boton_Jugar_Dificultad4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Jugar_Dificultad4x4ActionPerformed
        Ventana_Dificultad_4x4 Ventana = new Ventana_Dificultad_4x4();
        Ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_Boton_Jugar_Dificultad4x4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Nivel_De_Dificultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Nivel_De_Dificultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Nivel_De_Dificultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Nivel_De_Dificultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana_Nivel_De_Dificultad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Jugar_Dificultad3x3;
    private javax.swing.JButton Boton_Jugar_Dificultad4x4;
    private javax.swing.JButton Boton_VistaPrevia3x3;
    private javax.swing.JButton Boton_VistaPrevia4x4;
    private javax.swing.JButton Boton_Volver_Al_Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
