/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

/**
 *
 * @author aleja
 */
public class Ventana_Dificultad_4x4 extends javax.swing.JFrame {
    static int contador =1;
    int i=0;

    /**
     * Creates new form Ventana_de_Consulta_de_Saldo
     */
    public Ventana_Dificultad_4x4() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("The Puzzle Game - Juego de 4x4");
        Diesiseis.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Boton_Volver_al_menu = new javax.swing.JButton();
        Area_del_juego4x4 = new javax.swing.JPanel();
        Uno = new javax.swing.JButton();
        Dos = new javax.swing.JButton();
        Tres = new javax.swing.JButton();
        Cuatro = new javax.swing.JButton();
        Cinco = new javax.swing.JButton();
        Seis = new javax.swing.JButton();
        Siete = new javax.swing.JButton();
        Ocho = new javax.swing.JButton();
        Nueve = new javax.swing.JButton();
        Diez = new javax.swing.JButton();
        Once = new javax.swing.JButton();
        Doce = new javax.swing.JButton();
        Trece = new javax.swing.JButton();
        Catorce = new javax.swing.JButton();
        Quince = new javax.swing.JButton();
        Diesiseis = new javax.swing.JButton();
        Movimientos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtContador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(369, 70));
        setMinimumSize(new java.awt.Dimension(640, 640));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dificultad 4x4");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 20, 301, 35);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Coloca los numeros en orden de izquierda a derecha");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 510, 27);

        Boton_Volver_al_menu.setBackground(new java.awt.Color(102, 0, 204));
        Boton_Volver_al_menu.setFont(new java.awt.Font("Segoe UI Black", 0, 22)); // NOI18N
        Boton_Volver_al_menu.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Volver_al_menu.setText("<--Volver al menú");
        Boton_Volver_al_menu.setOpaque(false);
        Boton_Volver_al_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Volver_al_menuActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Volver_al_menu);
        Boton_Volver_al_menu.setBounds(40, 540, 240, 40);

        Area_del_juego4x4.setBackground(new java.awt.Color(255, 255, 153));
        Area_del_juego4x4.setLayout(new java.awt.GridLayout(4, 4));

        Uno.setBackground(new java.awt.Color(255, 153, 0));
        Uno.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Uno.setForeground(new java.awt.Color(255, 255, 255));
        Uno.setText("4");
        Uno.setBorder(null);
        Uno.setOpaque(false);
        Uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnoActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Uno);

        Dos.setBackground(new java.awt.Color(255, 153, 0));
        Dos.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Dos.setForeground(new java.awt.Color(255, 255, 255));
        Dos.setText("12");
        Dos.setOpaque(false);
        Dos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DosFocusGained(evt);
            }
        });
        Dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Dos);

        Tres.setBackground(new java.awt.Color(255, 153, 0));
        Tres.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Tres.setForeground(new java.awt.Color(255, 255, 255));
        Tres.setText("7");
        Tres.setOpaque(false);
        Tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TresActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Tres);

        Cuatro.setBackground(new java.awt.Color(255, 153, 0));
        Cuatro.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Cuatro.setForeground(new java.awt.Color(255, 255, 255));
        Cuatro.setText("3");
        Cuatro.setOpaque(false);
        Cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuatroActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Cuatro);

        Cinco.setBackground(new java.awt.Color(255, 153, 0));
        Cinco.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Cinco.setForeground(new java.awt.Color(255, 255, 255));
        Cinco.setText("1");
        Cinco.setOpaque(false);
        Cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CincoActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Cinco);

        Seis.setBackground(new java.awt.Color(255, 153, 0));
        Seis.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Seis.setForeground(new java.awt.Color(255, 255, 255));
        Seis.setText("9");
        Seis.setOpaque(false);
        Seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeisActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Seis);

        Siete.setBackground(new java.awt.Color(255, 153, 0));
        Siete.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Siete.setForeground(new java.awt.Color(255, 255, 255));
        Siete.setText("6");
        Siete.setOpaque(false);
        Siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SieteActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Siete);

        Ocho.setBackground(new java.awt.Color(255, 153, 0));
        Ocho.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Ocho.setForeground(new java.awt.Color(255, 255, 255));
        Ocho.setText("11");
        Ocho.setOpaque(false);
        Ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OchoActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Ocho);

        Nueve.setBackground(new java.awt.Color(255, 153, 0));
        Nueve.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Nueve.setForeground(new java.awt.Color(255, 255, 255));
        Nueve.setText("5");
        Nueve.setOpaque(false);
        Nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NueveActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Nueve);

        Diez.setBackground(new java.awt.Color(255, 153, 0));
        Diez.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Diez.setForeground(new java.awt.Color(255, 255, 255));
        Diez.setText("8");
        Diez.setOpaque(false);
        Diez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiezActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Diez);

        Once.setBackground(new java.awt.Color(255, 153, 0));
        Once.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Once.setForeground(new java.awt.Color(255, 255, 255));
        Once.setText("14");
        Once.setOpaque(false);
        Once.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnceActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Once);

        Doce.setBackground(new java.awt.Color(255, 153, 0));
        Doce.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Doce.setForeground(new java.awt.Color(255, 255, 255));
        Doce.setText("2");
        Doce.setOpaque(false);
        Doce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoceActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Doce);

        Trece.setBackground(new java.awt.Color(255, 153, 0));
        Trece.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Trece.setForeground(new java.awt.Color(255, 255, 255));
        Trece.setText("10");
        Trece.setOpaque(false);
        Trece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreceActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Trece);

        Catorce.setBackground(new java.awt.Color(255, 153, 0));
        Catorce.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Catorce.setForeground(new java.awt.Color(255, 255, 255));
        Catorce.setText("13");
        Catorce.setOpaque(false);
        Catorce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatorceActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Catorce);

        Quince.setBackground(new java.awt.Color(255, 153, 0));
        Quince.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Quince.setForeground(new java.awt.Color(255, 255, 255));
        Quince.setText("15");
        Quince.setOpaque(false);
        Quince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuinceActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Quince);

        Diesiseis.setBackground(new java.awt.Color(255, 153, 0));
        Diesiseis.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        Diesiseis.setForeground(new java.awt.Color(255, 255, 255));
        Diesiseis.setText("16");
        Diesiseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiesiseisActionPerformed(evt);
            }
        });
        Area_del_juego4x4.add(Diesiseis);

        getContentPane().add(Area_del_juego4x4);
        Area_del_juego4x4.setBounds(20, 140, 410, 370);

        Movimientos.setBackground(new java.awt.Color(5, 5, 70));
        Movimientos.setOpaque(false);
        Movimientos.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(0, 51, 153));
        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Movimientos");
        jLabel4.setOpaque(true);
        Movimientos.add(jLabel4);
        jLabel4.setBounds(0, 0, 170, 30);

        txtContador.setEditable(false);
        txtContador.setBackground(new java.awt.Color(0, 0, 153));
        txtContador.setFont(new java.awt.Font("Courier New", 1, 32)); // NOI18N
        txtContador.setForeground(new java.awt.Color(51, 255, 0));
        txtContador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0), 2));
        txtContador.setOpaque(false);
        txtContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContadorActionPerformed(evt);
            }
        });
        Movimientos.add(txtContador);
        txtContador.setBounds(10, 40, 70, 40);

        getContentPane().add(Movimientos);
        Movimientos.setBounds(440, 140, 180, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_del_puzzle/pngtree-modern-dark-color-abstract.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(640, 640));
        jLabel3.setMinimumSize(new java.awt.Dimension(640, 640));
        jLabel3.setName(""); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(640, 640));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 640, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuatroActionPerformed
        if (Tres.isVisible()==false) {
            Tres.setText(Cuatro.getText());
            Tres.setIcon(Cuatro.getIcon());
            Cuatro.setVisible(false);
            Tres.setVisible(true);
        }
        if (Ocho.isVisible()==false) {
            Ocho.setText(Cuatro.getText());
            Ocho.setIcon(Cuatro.getIcon());
            Cuatro.setVisible(false);
            Ocho.setVisible(true);
        }
        
        contarMovimiento();
    }//GEN-LAST:event_CuatroActionPerformed
    private void contarMovimiento() {
    txtContador.setText(String.valueOf(contador++));
    }
    private void DosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DosFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DosFocusGained

    private void UnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnoActionPerformed
        if (Dos.isVisible()==false) {
            Dos.setText(Uno.getText());
            Dos.setIcon(Uno.getIcon());
            Uno.setVisible(false);
            Dos.setVisible(true);
        }
        if (Cinco.isVisible()==false) {
            Cinco.setText(Uno.getText());
            Cinco.setIcon(Uno.getIcon());
            Uno.setVisible(false);
            Cinco.setVisible(true);
        }
        contarMovimiento();
    }//GEN-LAST:event_UnoActionPerformed

    private void TresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TresActionPerformed
        if (Dos.isVisible()==false) {
            Dos.setText(Tres.getText());
            Dos.setIcon(Tres.getIcon());
            Tres.setVisible(false);
            Dos.setVisible(true);
        }
        if (Cuatro.isVisible()==false) {
            Cuatro.setText(Tres.getText());
            Cuatro.setIcon(Tres.getIcon());
            Tres.setVisible(false);
            Cuatro.setVisible(true);
        }
        if (Siete.isVisible()==false) {
            Siete.setText(Tres.getText());
            Siete.setIcon(Tres.getIcon());
            Tres.setVisible(false);
            Siete.setVisible(true);
        }
        contarMovimiento();
    }//GEN-LAST:event_TresActionPerformed

    private void SeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeisActionPerformed
        if (Dos.isVisible()==false) {
            Dos.setText(Seis.getText());
            Dos.setIcon(Seis.getIcon());
            Seis.setVisible(false);
            Dos.setVisible(true);
        }
        if (Cinco.isVisible()==false) {
            Cinco.setText(Seis.getText());
            Cinco.setIcon(Seis.getIcon());
            Seis.setVisible(false);
            Cinco.setVisible(true);
        }
        if (Siete.isVisible()==false) {
            Siete.setText(Seis.getText());
            Siete.setIcon(Seis.getIcon());
            Seis.setVisible(false);
            Siete.setVisible(true);
        }
        if (Cinco.isVisible()==false) {
            Cinco.setText(Seis.getText());
            Cinco.setIcon(Seis.getIcon());
            Seis.setVisible(false);
            Cinco.setVisible(true);
        }
        if (Diez.isVisible()==false) {
            Diez.setText(Seis.getText());
            Diez.setIcon(Seis.getIcon());
            Seis.setVisible(false);
            Diez.setVisible(true);
        }
        
        contarMovimiento();
    }//GEN-LAST:event_SeisActionPerformed

    private void CincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CincoActionPerformed
        if (Uno.isVisible()==false) {
            Uno.setText(Cinco.getText());
            Uno.setIcon(Cinco.getIcon());
            Cinco.setVisible(false);
            Cinco.setVisible(true);
        }
        if (Seis.isVisible()==false) {
            Seis.setText(Cinco.getText());
            Seis.setIcon(Cinco.getIcon());
            Cinco.setVisible(false);
            Seis.setVisible(true);
        }
        if (Nueve.isVisible()==false) {
            Nueve.setText(Cinco.getText());
            Nueve.setIcon(Cinco.getIcon());
            Cinco.setVisible(false);
            Nueve.setVisible(true);
        }
        contarMovimiento();
    }//GEN-LAST:event_CincoActionPerformed

    private void OchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OchoActionPerformed
        if (Cuatro.isVisible()==false) {
            Cuatro.setText(Ocho.getText());
            Cuatro.setIcon(Ocho.getIcon());
            Ocho.setVisible(false);
            Cuatro.setVisible(true);
        }
        if (Siete.isVisible()==false) {
            Siete.setText(Ocho.getText());
            Siete.setIcon(Ocho.getIcon());
            Ocho.setVisible(false);
            Siete.setVisible(true);
        }
        if (Doce.isVisible()==false) {
            Doce.setText(Ocho.getText());
            Doce.setIcon(Ocho.getIcon());
            Ocho.setVisible(false);
            Doce.setVisible(true);
        }
        contarMovimiento();
    }//GEN-LAST:event_OchoActionPerformed

    private void NueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NueveActionPerformed
        if (Cinco.isVisible()==false) {
            Cinco.setText(Nueve.getText());
            Cinco.setIcon(Nueve.getIcon());
            Nueve.setVisible(false);
            Cinco.setVisible(true);
        }
        if (Diez.isVisible()==false) {
            Diez.setText(Nueve.getText());
            Diez.setIcon(Nueve.getIcon());
            Nueve.setVisible(false);
            Diez.setVisible(true);
        }
        if (Trece.isVisible()==false) {
            Trece.setText(Nueve.getText());
            Trece.setIcon(Nueve.getIcon());
            Nueve.setVisible(false);
            Trece.setVisible(true);
        }
        
        contarMovimiento();
    }//GEN-LAST:event_NueveActionPerformed

    private void DiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiezActionPerformed
        if (Catorce.isVisible()==false) {
            Catorce.setText(Diez.getText());
            Catorce.setIcon(Diez.getIcon());
            Diez.setVisible(false);
            Catorce.setVisible(true);
        }
        if (Seis.isVisible()==false) {
            Seis.setText(Diez.getText());
            Seis.setIcon(Diez.getIcon());
            Diez.setVisible(false);
            Seis.setVisible(true);
        }
        if (Once.isVisible()==false) {
            Once.setText(Diez.getText());
            Once.setIcon(Diez.getIcon());
            Diez.setVisible(false);
            Once.setVisible(true);
        }
        if (Nueve.isVisible()==false) {
            Nueve.setText(Diez.getText());
            Nueve.setIcon(Diez.getIcon());
            Diez.setVisible(false);
            Nueve.setVisible(true);
        }
        contarMovimiento();
    }//GEN-LAST:event_DiezActionPerformed

    private void OnceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnceActionPerformed
        if (Quince.isVisible()==false) {
            Quince.setText(Once.getText());
            Quince.setIcon(Once.getIcon());
            Once.setVisible(false);
            Quince.setVisible(true);
        }
        if (Doce.isVisible()==false) {
            Doce.setText(Once.getText());
            Doce.setIcon(Once.getIcon());
            Once.setVisible(false);
            Doce.setVisible(true);
        }
        if (Diez.isVisible()==false) {
            Diez.setText(Once.getText());
            Diez.setIcon(Once.getIcon());
            Once.setVisible(false);
            Diez.setVisible(true);
        }
        if (Siete.isVisible()==false) {
            Siete.setText(Once.getText());
            Siete.setIcon(Once.getIcon());
            Once.setVisible(false);
            Siete.setVisible(true);
        }
        contarMovimiento();
    }//GEN-LAST:event_OnceActionPerformed

    private void DoceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoceActionPerformed
        if (Diesiseis.isVisible()==false) {
            Diesiseis.setText(Doce.getText());
            Diesiseis.setIcon(Doce.getIcon());
            Doce.setVisible(false);
            Diesiseis.setVisible(true);
        }
        if (Ocho.isVisible()==false) {
            Ocho.setText(Doce.getText());
            Ocho.setIcon(Doce.getIcon());
            Doce.setVisible(false);
            Ocho.setVisible(true);
        }
        if (Once.isVisible()==false) {
            Once.setText(Doce.getText());
            Once.setIcon(Doce.getIcon());
            Doce.setVisible(false);
            Once.setVisible(true);
        }
        
        contarMovimiento();
    }//GEN-LAST:event_DoceActionPerformed

    private void TreceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreceActionPerformed
        
        contarMovimiento();
    }//GEN-LAST:event_TreceActionPerformed

    private void Boton_Volver_al_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Volver_al_menuActionPerformed
        Ventana_MenuPrincipal_Juego Ventana = new Ventana_MenuPrincipal_Juego();
        Ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_Boton_Volver_al_menuActionPerformed

    private void CatorceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatorceActionPerformed
        if (Quince.isVisible()==false) {
            Quince.setText(Catorce.getText());
            Quince.setIcon(Catorce.getIcon());
            Catorce.setVisible(false);
            Quince.setVisible(true);
        }
        if (Diez.isVisible()==false) {
            Diez.setText(Catorce.getText());
            Diez.setIcon(Catorce.getIcon());
            Catorce.setVisible(false);
            Diez.setVisible(true);
        }
        if (Trece.isVisible()==false) {
            Trece.setText(Catorce.getText());
            Trece.setIcon(Catorce.getIcon());
            Catorce.setVisible(false);
            Trece.setVisible(true);
        }
        
        contarMovimiento();
    }//GEN-LAST:event_CatorceActionPerformed

    private void QuinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuinceActionPerformed
        if (Diesiseis.isVisible()==false) {
            Diesiseis.setText(Quince.getText());
            Diesiseis.setIcon(Quince.getIcon());
            Quince.setVisible(false);
            Diesiseis.setVisible(true);
        }
        if (Catorce.isVisible()==false) {
            Catorce.setText(Quince.getText());
            Catorce.setIcon(Quince.getIcon());
            Quince.setVisible(false);
            Catorce.setVisible(true);
        }
        if (Once.isVisible()==false) {
            Once.setText(Quince.getText());
            Once.setIcon(Quince.getIcon());
            Quince.setVisible(false);
            Once.setVisible(true);
        }
        contarMovimiento();
    }//GEN-LAST:event_QuinceActionPerformed

    private void txtContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContadorActionPerformed

    private void DosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosActionPerformed
        if (Uno.isVisible()==false) {
            Uno.setText(Dos.getText());
            Uno.setIcon(Dos.getIcon());
            Dos.setVisible(false);
            Uno.setVisible(true);
        }
        if (Tres.isVisible()==false) {
            Tres.setText(Dos.getText());
            Tres.setIcon(Dos.getIcon());
            Dos.setVisible(false);
            Tres.setVisible(true);
        }
        if (Seis.isVisible()==false) {
            Seis.setText(Dos.getText());
            Seis.setIcon(Dos.getIcon());
            Dos.setVisible(false);
            Seis.setVisible(true);
        }
        contarMovimiento();
    }//GEN-LAST:event_DosActionPerformed

    private void SieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SieteActionPerformed
        if (Tres.isVisible()==false) {
            Tres.setText(Siete.getText());
            Tres.setIcon(Siete.getIcon());
            Siete.setVisible(false);
            Tres.setVisible(true);
        }
        if (Seis.isVisible()==false) {
            Seis.setText(Siete.getText());
            Seis.setIcon(Siete.getIcon());
            Siete.setVisible(false);
            Seis.setVisible(true);
        }
        if (Ocho.isVisible()==false) {
            Ocho.setText(Siete.getText());
            Ocho.setIcon(Siete.getIcon());
            Siete.setVisible(false);
            Ocho.setVisible(true);
        }
        if (Once.isVisible()==false) {
            Once.setText(Siete.getText());
            Once.setIcon(Siete.getIcon());
            Siete.setVisible(false);
            Once.setVisible(true);
        }
        
        contarMovimiento();
    }//GEN-LAST:event_SieteActionPerformed

    private void DiesiseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiesiseisActionPerformed
        if (Doce.isVisible()==false) {
            Doce.setText(Diesiseis.getText());
            Doce.setIcon(Diesiseis.getIcon());
            Diesiseis.setVisible(false);
            Doce.setVisible(true);
        }
        if (Quince.isVisible()==false) {
            Quince.setText(Diesiseis.getText());
            Diesiseis.setIcon(Diesiseis.getIcon());
            Diesiseis.setVisible(false);
            Quince.setVisible(true);
        }
        contarMovimiento();
    }//GEN-LAST:event_DiesiseisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Dificultad_4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Dificultad_4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Dificultad_4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Dificultad_4x4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana_Dificultad_4x4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Area_del_juego4x4;
    private javax.swing.JButton Boton_Volver_al_menu;
    private javax.swing.JButton Catorce;
    private javax.swing.JButton Cinco;
    private javax.swing.JButton Cuatro;
    private javax.swing.JButton Diesiseis;
    private javax.swing.JButton Diez;
    private javax.swing.JButton Doce;
    private javax.swing.JButton Dos;
    private javax.swing.JPanel Movimientos;
    private javax.swing.JButton Nueve;
    private javax.swing.JButton Ocho;
    private javax.swing.JButton Once;
    private javax.swing.JButton Quince;
    private javax.swing.JButton Seis;
    private javax.swing.JButton Siete;
    private javax.swing.JButton Trece;
    private javax.swing.JButton Tres;
    private javax.swing.JButton Uno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtContador;
    // End of variables declaration//GEN-END:variables
}
